// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQIRhOCc3E6OZNKt9ATADEmWqmo60y4ys',
    appId: '1:614215162838:web:d77fdeb6e0ec4d51456277',
    messagingSenderId: '614215162838',
    projectId: 'helloworld-ad78a',
    authDomain: 'helloworld-ad78a.firebaseapp.com',
    storageBucket: 'helloworld-ad78a.firebasestorage.app',
    measurementId: 'G-4QGPY015LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9j5hMPOI2VvC97YQO7UeU92FCyvrAwQ4',
    appId: '1:614215162838:android:b45e4e3b706e615e456277',
    messagingSenderId: '614215162838',
    projectId: 'helloworld-ad78a',
    storageBucket: 'helloworld-ad78a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxKcOcwU0oopo3H7TAyPuQ4ZF8IEZbh5Q',
    appId: '1:614215162838:ios:0176577f4d02359b456277',
    messagingSenderId: '614215162838',
    projectId: 'helloworld-ad78a',
    storageBucket: 'helloworld-ad78a.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxKcOcwU0oopo3H7TAyPuQ4ZF8IEZbh5Q',
    appId: '1:614215162838:ios:0176577f4d02359b456277',
    messagingSenderId: '614215162838',
    projectId: 'helloworld-ad78a',
    storageBucket: 'helloworld-ad78a.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQIRhOCc3E6OZNKt9ATADEmWqmo60y4ys',
    appId: '1:614215162838:web:65e7c6212e808ddd456277',
    messagingSenderId: '614215162838',
    projectId: 'helloworld-ad78a',
    authDomain: 'helloworld-ad78a.firebaseapp.com',
    storageBucket: 'helloworld-ad78a.firebasestorage.app',
    measurementId: 'G-9B4MKVMPH0',
  );
}
